<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    /// XXX TO BE MOVED to appropriate places
    'Balance: {balance}' => 'Баланс: {balance}',
    'Check domain' => 'Проверить домен',
    'Create ticket' => 'Создать тикет',
    'Credit: {credit}' => 'Кредит: {credit}',
    'Recharge account' => 'Пополнить счёт',

    /// Home
    'Home' => 'Главная',
    'Profile' => 'Профиль',

    /// Действия
    'Save' => 'Сохранить',
    'Send' => 'Отправить',
    'Confirm' => 'Подтвердить',
    'Confirm connect social' => 'Подтвердить подключение',

    /// Логин
    'Sign in' => 'Войти',
    'Sign in to start your session' => 'Войдите чтобы начать работу',
    'Sign out' => 'Выйти',
    'Signup' => 'Зарегистрироваться',
    'Email' => 'Email',
    'Login or Email' => 'Логин или Email',
    'OR SIGN IN WITH' => 'ИЛИ ВОЙДИТЕ С ПОМОЩЬЮ',

    /// Пароль
    'Password' => 'Пароль',
    'Please choose your new password' => 'Пожалуйста, выберите новый пароль',
    'I forgot my password' => 'Я забыл мой пароль',
    'Request password reset' => 'Запросить сброс пароля',
    'Reset password' => 'Сбросить пароль',

    /// Регистрация
    'Register a new membership' => 'Зарегистрироваться',
    'I agree to the' => 'Я согласен с',
    'terms' => 'условиями',
    'I already have a membership' => 'Я уже зарегистрирован',
    'Please fill out the following fields to signup' => 'Пожалуйста, заполните поля для регистрации',

    /// Настройки
    'Skins'             => 'Темы оформления',
    'Black'             => 'Черная',
    'Blue'              => 'Синяя',
    'Ebony'             => 'Эбонитовая',
    'Green'             => 'Зеленая',
    'Purple'            => 'Фиолетовая',
    'Red'               => 'Красная',
    'Yellow'            => 'Желтая',
    'Layout'            => 'Вёрстка',
    'Layout Settings'   => 'Настройки макета',
    'Default layout'    => 'Стандартная',
    'Boxed layout'      => 'Компактная',
    'Fixed layout'      => 'Фиксированная',
    'Table Condensed'   => 'Компактная Таблица',
    'Table height'      => 'Высота таблицы',
    'Sidebar'           => 'Боковая панель',
    'Collapsed Sidebar' => 'Свернутая боковая панель',
    'Sidebar'           => 'Боковая панель',

    /// Ошибки
    'The above error occurred while the Web server was processing your request.' => 'Во время обработки вашего запроса произошла ошибка.',
    'Please contact us if you think this is a server error. Thank you.' => 'Пожалуйста, свяжитесь с нами, если вы считаете что это ошибка сервера. Спасибо.',

];
