<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Balance: {balance}' => 'Баланс: {balance}',
    'Blue' => 'Синяя',
    'Check domain' => 'Проверить домен',
    'Collapsed Sidebar' => 'Свернутая боковая панель',
    'Create ticket' => 'Создать тикет',
    'Credit: {credit}' => 'Кредит: {credit}',
    'Default layout' => 'Стандартная',
    'Fixed layout' => 'Фиксированная',
    'Green' => 'Зеленая',
    'Home' => 'Главная',
    'Layout' => 'Вёрстка',
    'OR SIGN IN WITH' => 'ИЛИ ВОЙТИ ЧЕРЕЗ',
    'Please contact us if you think this is a server error. Thank you.' => 'Пожалуйста, свяжитесь с нами, если вы считаете что это ошибка сервера. Спасибо.',
    'Profile' => 'Профиль',
    'Purple' => 'Фиолетовая',
    'Recharge account' => 'Пополнить счёт',
    'Red' => 'Красная',
    'Save' => 'Сохранить',
    'Sidebar' => 'Боковая панель',
    'Sign out' => 'Выйти',
    'Skins' => 'Темы оформления',
    'Table Condensed' => 'Компактная Таблица',
    'Table height' => 'Высота таблицы',
    'The above error occurred while the Web server was processing your request.' => 'Во время обработки вашего запроса произошла ошибка.',
    'Yellow' => 'Желтая',
];
