<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Balance: {balance}' => 'Баланс: {balance}',
    'Black' => 'Черная',
    'Blue' => 'Синяя',
    'Boxed layout' => 'Компактная',
    'Check domain' => 'Проверить домен',
    'Collapsed Sidebar' => 'Свернутая боковая панель',
    'Confirm' => 'Подтвердить',
    'Confirm connect social' => 'Подтвердить подключение',
    'Create ticket' => 'Создать тикет',
    'Credit: {credit}' => 'Кредит: {credit}',
    'Default layout' => 'Стандартная',
    'Ebony' => 'Эбонитовая',
    'Email' => 'Email',
    'Fixed layout' => 'Фиксированная',
    'Green' => 'Зеленая',
    'Home' => 'Главная',
    'I agree to the' => 'Я согласен с',
    'I already have a membership' => 'Я уже зарегистрирован',
    'I forgot my password' => 'Я забыл мой пароль',
    'Layout' => 'Вёрстка',
    'Layout Settings' => 'Настройки макета',
    'Login or Email' => 'Логин или Email',
    'OR SIGN IN WITH' => 'ИЛИ ВОЙДИТЕ С ПОМОЩЬЮ',
    'Password' => 'Пароль',
    'Please choose your new password' => 'Пожалуйста, выберите новый пароль',
    'Please contact us if you think this is a server error. Thank you.' => 'Пожалуйста, свяжитесь с нами, если вы считаете что это ошибка сервера. Спасибо.',
    'Please fill out the following fields to signup' => 'Пожалуйста, заполните поля для регистрации',
    'Profile' => 'Профиль',
    'Purple' => 'Фиолетовая',
    'Recharge account' => 'Пополнить счёт',
    'Red' => 'Красная',
    'Register a new membership' => 'Зарегистрироваться',
    'Request password reset' => 'Запросить сброс пароля',
    'Reset password' => 'Сбросить пароль',
    'Save' => 'Сохранить',
    'Send' => 'Отправить',
    'Sidebar' => 'Боковая панель',
    'Sign in' => 'Войти',
    'Sign in to start your session' => 'Войдите чтобы начать работу',
    'Sign out' => 'Выйти',
    'Signup' => 'Зарегистрироваться',
    'Skins' => 'Темы оформления',
    'Table Condensed' => 'Компактная Таблица',
    'Table height' => 'Высота таблицы',
    'The above error occurred while the Web server was processing your request.' => 'Во время обработки вашего запроса произошла ошибка.',
    'Yellow' => 'Желтая',
    'terms' => 'условиями',
];
